# Generated by Django 6.0.6 on 2026-08-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_workers', models.IntegerField(default=0)),
                ('total_clients', models.IntegerField(default=0)),
                ('total_both_roles', models.IntegerField(default=0)),
                ('verified_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('new_workers', models.IntegerField(default=0)),
                ('new_clients', models.IntegerField(default=0)),
                ('total_jobs', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('jobs_cancelled', models.IntegerField(default=0)),
                ('open_jobs', models.IntegerField(default=0)),
                ('assigned_jobs', models.IntegerField(default=0)),
                ('in_progress_jobs', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('reviews_created', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_distribution', models.JSONField(default=dict)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Stat',
                'verbose_name_plural': 'Daily Stats',
                'db_table': 'analytics_daily_stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_26c219_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('month', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('reviews_created', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Stat',
                'verbose_name_plural': 'Monthly Stats',
                'db_table': 'analytics_monthly_stats',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='analytics_m_month_140436_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('jobs_viewed', models.IntegerField(default=0)),
                ('jobs_applied', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('reviews_given', models.IntegerField(default=0)),
                ('reviews_received', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('session_count', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'analytics_user_activity',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_u_user_id_015ec2_idx'), models.Index(fields=['date'], name='analytics_u_date_becc5f_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('reviews_created', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Stat',
                'verbose_name_plural': 'Weekly Stats',
                'db_table': 'analytics_weekly_stats',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start'], name='analytics_w_week_st_90ad7c_idx')],
            },
        ),
    ]
