# Generated by Django 6.0.6 on 2026-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the record was soft-deleted', null=True)),
                ('title', models.CharField(help_text='Notification title', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('JOB_POSTED', 'Job Posted'), ('APPLICATION_RECEIVED', 'Application Received'), ('WORKER_ASSIGNED', 'Worker Assigned'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_CANCELLED', 'Job Cancelled'), ('REPORT_RESOLVED', 'Report Resolved'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_BANNED', 'Account Banned'), ('WARNING_ISSUED', 'Warning Issued')], help_text='Type of notification', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('related_entity_id', models.IntegerField(blank=True, help_text='ID of the related entity (job, report, etc.)', null=True)),
                ('related_entity_type', models.CharField(blank=True, help_text='Type of the related entity', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('recipient', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx')],
            },
        ),
    ]
