# Generated by Django 6.0.6 on 2026-08-30 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='in_app_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('JOB_POSTED', 'Job Posted'), ('JOB_ASSIGNED', 'Job Assigned'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_CONFIRMED', 'Job Confirmed'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('REVIEW_RECEIVED', 'Review Received'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('REPORT_RESOLVED', 'Report Resolved'), ('WORKER_APPLIED', 'Worker Applied'), ('SYSTEM', 'System')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
    ]
