# Generated by Django 6.0.6 on 2026-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('JOB_POSTED', 'Job Posted'), ('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('WORKER_ASSIGNED', 'Worker Assigned'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_CANCELLED', 'Job Cancelled'), ('REPORT_RESOLVED', 'Report Resolved'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_BANNED', 'Account Banned'), ('WARNING_ISSUED', 'Warning Issued')], max_length=30),
        ),
    ]
