# Generated by Django 6.0.6 on 2026-09-21 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('WORKER', 'Worker'), ('ADMIN', 'Admin')], db_index=True, help_text='The role this notification is intended for. Null = role-agnostic (shown on every dashboard).', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'role', 'is_read'], name='notificatio_recipie_6d4748_idx'),
        ),
    ]
