# Generated by Django 6.0.6 on 2026-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the record was soft-deleted', null=True)),
                ('document_type', models.CharField(choices=[('NRC', 'National Registration Card'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License")], help_text='Type of identification document', max_length=20)),
                ('document_number', models.CharField(help_text='Document identification number', max_length=100)),
                ('front_document_path', models.CharField(help_text='Path to front document image', max_length=500)),
                ('back_document_path', models.CharField(blank=True, help_text='Path to back document image (optional)', max_length=500)),
                ('selfie_photo_path', models.CharField(blank=True, help_text="Path to user's selfie photo (optional)", max_length=500)),
                ('verification_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SUBMITTED', help_text='Current verification status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When documents were submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the verification was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('verification_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to='accounts.user')),
                ('user', models.ForeignKey(help_text='User requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to='accounts.user')),
            ],
            options={
                'db_table': 'identity_verifications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'verification_status'], name='identity_ve_user_id_3a1937_idx'), models.Index(fields=['verification_status', 'submitted_at'], name='identity_ve_verific_47c305_idx')],
            },
        ),
    ]
