# Generated by Django 6.0.6 on 2026-07-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('NRC_FRONT', 'NRC Front'), ('NRC_BACK', 'NRC Back'), ('PASSPORT_PHOTO', 'Passport Photo'), ('SELFIE', 'Selfie')], max_length=20)),
                ('document_number', models.CharField(max_length=100)),
                ('verification_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SUBMITTED', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to='accounts.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Identity Verification',
                'verbose_name_plural': 'Identity Verifications',
                'db_table': 'identity_verifications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NRC_FRONT', 'NRC Front'), ('NRC_BACK', 'NRC Back'), ('PASSPORT_PHOTO', 'Passport Photo'), ('SELFIE', 'Selfie')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='identity_verification.identityverification')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'verification_documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['user', 'verification_status'], name='identity_ve_user_id_3a1937_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['verification_status', 'submitted_at'], name='identity_ve_verific_47c305_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['verification', 'document_type'], name='verificatio_verific_a18463_idx'),
        ),
    ]
