# Generated by Django 6.0.6 on 2026-09-15 22:28

import apps.identity_verification.models.verification_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationdocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.identity_verification.models.verification_document.verification_doc_path),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
