# Generated by Django 6.0.6 on 2026-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('WARN', 'Warning'), ('SUSPEND', 'Suspend'), ('BAN', 'Ban'), ('UNBAN', 'Unban'), ('VERIFY', 'Verify'), ('REJECT_VERIFICATION', 'Reject Verification'), ('DISMISS_REPORT', 'Dismiss Report')], help_text='Type of admin action', max_length=30)),
                ('reason', models.TextField(help_text='Reason for the action')),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the action expires (for temporary suspensions)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('admin', models.ForeignKey(help_text='Admin who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='actions_taken', to='accounts.user')),
                ('related_report', models.ForeignKey(blank=True, help_text='Report that triggered this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='reports.report')),
                ('target_user', models.ForeignKey(help_text='User the action was taken against', on_delete=django.db.models.deletion.CASCADE, related_name='actions_received', to='accounts.user')),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['target_user', 'performed_at'], name='admin_actio_target__595dcd_idx'), models.Index(fields=['action_type', 'expires_at'], name='admin_actio_action__acd24b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed (e.g., USER_REGISTERED, JOB_POSTED)', max_length=100)),
                ('entity_type', models.CharField(help_text='Type of entity affected (e.g., USER, JOB, REPORT)', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of the affected entity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details (before/after values, metadata)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the action was logged')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (nullable for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_logs_entity__3d1d1b_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx')],
            },
        ),
    ]
