# Generated by Django 6.0.6 on 2026-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='action_type',
            field=models.CharField(choices=[('WARNING', 'Warning'), ('SUSPEND', 'Suspension'), ('PERMANENT_BAN', 'Permanent Ban')], max_length=20),
        ),
    ]
