# Generated by Django 6.0.6 on 2026-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_disciplinaryaction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='action_type',
            field=models.CharField(choices=[('WARN', 'Warning'), ('SUSPEND', 'Suspend'), ('BAN', 'Ban'), ('UNBAN', 'Unban'), ('VERIFY', 'Verify'), ('REJECT_VERIFICATION', 'Reject Verification'), ('DISMISS_REPORT', 'Dismiss Report')], max_length=20),
        ),
    ]
