# Generated by Django 6.0.6 on 2026-09-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_ban_reason_user_banned_at_user_suspended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
