# Generated by Django 6.0.6 on 2026-09-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_location_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating received from workers who completed jobs for this client.', max_digits=3),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='total_reviews',
            field=models.IntegerField(default=0, help_text='Number of reviews received from workers.'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['average_rating'], name='client_prof_average_9a1e6e_idx'),
        ),
    ]
