# Generated by Django 6.0.6 on 2026-08-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('USER_STATS', 'User Statistics'), ('JOB_STATS', 'Job Statistics'), ('REVIEW_STATS', 'Review Statistics'), ('REVENUE_STATS', 'Revenue Statistics'), ('RECENT_ACTIVITY', 'Recent Activity'), ('PENDING_VERIFICATIONS', 'Pending Verifications'), ('REPORTS', 'Reports'), ('DISCIPLINARY', 'Disciplinary Actions')], max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'dashboard_widgets',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('setting_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON'), ('DECIMAL', 'Decimal')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
