# Generated by Django 6.0.6 on 2026-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Plumbing, Electrical)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or path', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the record was soft-deleted', null=True)),
                ('title', models.CharField(help_text='Job title/summary', max_length=255)),
                ('description', models.TextField(help_text='Detailed job description')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Budget for the job', max_digits=10)),
                ('general_location', models.CharField(help_text='General area/neighborhood', max_length=255)),
                ('exact_location', models.CharField(blank=True, help_text='Exact address or landmark', max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', help_text='Current job status', max_length=20)),
                ('radius', models.IntegerField(default=5, help_text='Distance radius for worker matching (in km)')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='When the job was posted')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_worker', models.ForeignKey(blank=True, help_text='Worker assigned to this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to='accounts.user')),
                ('client', models.ForeignKey(help_text='Client who posted the job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='accounts.user')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('category', models.ForeignKey(help_text='Job category', on_delete=django.db.models.deletion.PROTECT, to='jobs.jobcategory')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', help_text='Application status', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, help_text='When the application was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('job', models.ForeignKey(help_text='Job being applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('worker', models.ForeignKey(help_text='Worker applying for the job', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='accounts.user')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'), models.Index(fields=['worker', 'status'], name='job_applica_worker__9a7b7f_idx')],
                'unique_together': {('job', 'worker')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'posted_at'], name='jobs_status_552bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client', 'status'], name='jobs_client__0133c6_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['assigned_worker', 'status'], name='jobs_assigne_1b2bb2_idx'),
        ),
    ]
