# Generated by Django 6.0.6 on 2026-08-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff_user_is_superuser_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='auto_confirm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_confirm_grace_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='job',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='client_confirmed_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='dispute_raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_raised', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dispute_resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dispute_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INVESTIGATING', 'Investigating'), ('RESOLVED_WORKER', 'Resolved - Worker at fault'), ('RESOLVED_CLIENT', 'Resolved - Client at fault'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estimated duration in hours (e.g., 2.5)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='escrow_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_flexible',
            field=models.BooleanField(default=True, help_text='Can the worker choose the exact time?'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(blank=True, help_text='Date when the job needs to be done', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_time',
            field=models.TimeField(blank=True, help_text='Time when the job should start', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount paid (may differ from budget)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('ESCROW', 'Escrow')], default='CASH', help_text='How the job is/was paid for', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference ID from payment gateway (future use)', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('ESCROW', 'In Escrow'), ('RELEASED', 'Released to Worker'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills required for this job (optional)', related_name='jobs', to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='timeframe',
            field=models.CharField(choices=[('MORNING', 'Morning (6AM - 12PM)'), ('AFTERNOON', 'Afternoon (12PM - 5PM)'), ('EVENING', 'Evening (5PM - 9PM)'), ('ANYTIME', 'Anytime')], default='ANYTIME', help_text='Preferred time of day', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='urgency',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate (Today)'), ('URGENT', 'Urgent (Within 3 days)'), ('NORMAL', 'Normal (Within a week)'), ('FLEXIBLE', 'Flexible (Any time)')], default='NORMAL', help_text='How urgent is the job?', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='worker_marked_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='worker_marked_complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='exact_location',
            field=models.CharField(blank=True, help_text='Specific address/landmark', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='general_location',
            field=models.CharField(help_text='Human-readable address (manual entry for display)', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Auto-detected from device GPS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Auto-detected from device GPS', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='radius',
            field=models.IntegerField(default=5, help_text='Search radius in kilometers'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_CONFIRMATION', 'Awaiting Confirmation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=25),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['urgency'], name='jobs_urgency_163975_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_date'], name='jobs_job_dat_081926_idx'),
        ),
    ]
