# Generated by Django 6.0.6 on 2026-08-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_auto_confirm_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='escrow_release_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='radius',
        ),
    ]
