# Generated by Django 6.0.6 on 2026-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_escrow_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='directions_url',
            field=models.URLField(blank=True, help_text='Directions URL from client location - HIDDEN from workers until assigned', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps/OpenStreetMap URL - HIDDEN from workers until assigned', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='place_id',
            field=models.CharField(blank=True, help_text='Google Maps Place ID for the exact location - HIDDEN from workers until assigned', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='exact_location',
            field=models.CharField(blank=True, help_text='Specific address/landmark - HIDDEN from workers until assigned', max_length=255),
        ),
    ]
