# Generated by Django 6.0.6 on 2026-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_directions_url_job_map_url_job_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
