# Generated by Django 6.0.6 on 2026-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='client_hidden_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the client hid this completed job from their dashboard. Used to declutter My Jobs without removing history.', null=True),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='worker_hidden_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the worker hid this assignment from their My Work page. Used to declutter work history without removing the record.', null=True),
        ),
    ]
