# Generated by Django 6.0.6 on 2026-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='job_completed',
            field=models.BooleanField(default=True, help_text='Whether the job was actually completed by the worker. If False, the rating must be 0.'),
        ),
    ]
