# Generated by Django 6.0.6 on 2026-07-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('THEFT', 'Theft'), ('VIOLENCE', 'Violence'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Fraud'), ('PROPERTY_DAMAGE', 'Property Damage'), ('NO_SHOW', 'No Show'), ('POOR_CONDUCT', 'Poor Conduct'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('AWAITING_USER_RESPONSE', 'Awaiting User Response'), ('RESOLVED', 'Resolved'), ('ESCALATED_TO_POLICE', 'Escalated to Police'), ('CLOSED', 'Closed')], default='PENDING', max_length=30)),
                ('police_report_generated', models.BooleanField(default=False)),
                ('police_report_path', models.CharField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='accounts.user')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('AWAITING_USER_RESPONSE', 'Awaiting User Response'), ('RESOLVED', 'Resolved'), ('ESCALATED_TO_POLICE', 'Escalated to Police'), ('CLOSED', 'Closed')], default='UNDER_INVESTIGATION', max_length=30)),
                ('decision', models.CharField(blank=True, choices=[('DISMISSED', 'Dismissed'), ('WARNED', 'Warned'), ('SUSPENDED', 'Suspended'), ('BANNED', 'Banned'), ('ESCALATED', 'Escalated')], max_length=20, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='accounts.user')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='reports.report')),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
                'db_table': 'investigations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_uploaded', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Report Evidence',
                'verbose_name_plural': 'Report Evidences',
                'db_table': 'report_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'submitted_at'], name='reports_status_784b46_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'status'], name='reports_reporte_432026_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reference_number'], name='reports_referen_f7f801_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['report', 'status'], name='investigati_report__355f64_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['admin', 'status'], name='investigati_admin_i_5fff70_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevidence',
            index=models.Index(fields=['report', 'uploaded_at'], name='report_evid_report__0a3c9d_idx'),
        ),
    ]
