# Generated by Django 6.0.6 on 2026-07-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the record was soft-deleted', null=True)),
                ('reference_number', models.CharField(help_text='Human-readable reference number (REP-2026-0015)', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('THEFT', 'Theft'), ('VIOLENCE', 'Violence'), ('HARASSMENT', 'Harassment'), ('FRAUD', 'Fraud'), ('PROPERTY_DAMAGE', 'Property Damage'), ('NO_SHOW', 'No Show'), ('POOR_CONDUCT', 'Poor Conduct'), ('OTHER', 'Other')], help_text='Type of report', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('AWAITING_USER_RESPONSE', 'Awaiting User Response'), ('RESOLVED', 'Resolved'), ('ESCALATED_TO_POLICE', 'Escalated to Police'), ('CLOSED', 'Closed')], default='PENDING', help_text='Current report status', max_length=30)),
                ('admin_decision', models.CharField(blank=True, choices=[('DISMISSED', 'Dismissed'), ('WARNED', 'Warned'), ('SUSPENDED', 'Suspended'), ('BANNED', 'Banned'), ('ESCALATED', 'Escalated')], help_text="Administrator's decision", max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes (not visible to users)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('decision_made_at', models.DateTimeField(blank=True, help_text='When the admin decision was made', null=True)),
                ('police_report_generated', models.BooleanField(default=False, help_text='Whether a police report has been generated')),
                ('police_report_path', models.CharField(blank=True, help_text='Path to generated police report PDF', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to='accounts.user')),
                ('job', models.ForeignKey(help_text='Job where incident occurred', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reported_user', models.ForeignKey(help_text='User being reported', on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='accounts.user')),
                ('reporter', models.ForeignKey(help_text='User reporting the incident', on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='accounts.user')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to='accounts.user')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the evidence file', max_length=500)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], help_text='Type of evidence file', max_length=20)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the evidence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the evidence was uploaded')),
                ('report', models.ForeignKey(help_text='Report this evidence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the evidence', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_uploaded', to='accounts.user')),
            ],
            options={
                'db_table': 'report_evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'submitted_at'], name='reports_status_784b46_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', 'status'], name='reports_reporte_432026_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reference_number'], name='reports_referen_f7f801_idx'),
        ),
        migrations.AddIndex(
            model_name='reportevidence',
            index=models.Index(fields=['report', 'uploaded_at'], name='report_evid_report__0a3c9d_idx'),
        ),
    ]
