# Generated by Django 6.0.6 on 2026-09-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportevidence',
            name='report_evid_report__0a3c9d_idx',
        ),
        migrations.DeleteModel(
            name='ReportEvidence',
        ),
    ]
