# Generated by Django 6.0.6 on 2026-09-21 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobcategory_parent_category_and_more'),
        ('reports', '0002_remove_reportevidence_report_evid_report__0a3c9d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Null for general complaints.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, help_text='Null for general complaints.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL),
        ),
    ]
